# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

inhibit_all_warnings! # This will disable all the warnings for all pods.

pod 'AFNetworking', '~> 2.5.2'
pod 'SDWebImage', '~> 3.7.2'
pod 'TPKeyboardAvoiding', '~> 1.2.6'
